<?php require_once __DIR__ . '/../../includes/auth.php'; require_login(); include __DIR__ . '/../../includes/header.php';
$rows=$pdo->query("SELECT a.*,e.nom,e.prenom,u.login enseignant FROM absences a JOIN etudiants e ON e.id=a.etudiant_id LEFT JOIN utilisateurs u ON u.id=a.enseignant_id ORDER BY a.date_absence DESC,a.heure_absence DESC")->fetchAll();
$s=$pdo->query("SELECT COUNT(*) total, SUM(etat='non_justifiee') nj, SUM(etat='justifiee') j FROM absences")->fetch();
?>
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="page-title">Absences</h1><a class="btn btn-primary" href="saisie.php"><i class="fa-solid fa-plus me-1"></i>Saisie</a></div>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card p-3"><b>Total</b><span class="fs-3"><?= $s['total']??0 ?></span></div></div><div class="col-md-4"><div class="card p-3"><b>Non justifiées</b><span class="fs-3"><?= $s['nj']??0 ?></span></div></div><div class="col-md-4"><div class="card p-3"><b>Justifiées</b><span class="fs-3"><?= $s['j']??0 ?></span></div></div></div>
<div class="table-responsive table-wrap bg-white p-3"><table class="table table-hover align-middle"><thead><tr><th>Étudiant</th><th>Date</th><th>Heure</th><th>Séance</th><th>Enseignant</th><th>État</th><th></th></tr></thead><tbody>
<?php foreach($rows as $r): ?><tr><td><?= e($r['nom'].' '.$r['prenom']) ?></td><td><?= e($r['date_absence']) ?></td><td><?= e($r['heure_absence']) ?></td><td><?= e($r['type_seance']) ?></td><td><?= e($r['enseignant']) ?></td><td><span class="badge bg-<?= $r['etat']==='justifiee'?'success':($r['etat']==='annulee'?'secondary':'danger') ?>"><?= e($r['etat']) ?></span></td><td class="text-end"><a class="btn btn-sm btn-success" href="justifier.php?id=<?= $r['id'] ?>"><i class="fa-solid fa-check"></i></a> <a onclick="return confirm('Annuler cette absence ?')" class="btn btn-sm btn-secondary" href="annuler.php?id=<?= $r['id'] ?>"><i class="fa-solid fa-ban"></i></a></td></tr><?php endforeach; ?>
</tbody></table></div><?php include __DIR__ . '/../../includes/footer.php'; ?>
