<?php require_once __DIR__ . '/../../includes/auth.php'; require_login(); $niveau=$_GET['niveau']??''; $msg='';
if ($_SERVER['REQUEST_METHOD']==='POST') { foreach($_POST['etudiants']??[] as $eid) $pdo->prepare("INSERT INTO absences(etudiant_id,enseignant_id,date_absence,heure_absence,type_seance,etat) VALUES(?,?,?,?,?,'non_justifiee')")->execute([(int)$eid,current_user()['id'],$_POST['date_absence'],$_POST['heure_absence'],$_POST['type_seance']]); $msg='Absences enregistrées.'; $niveau=$_POST['niveau']; }
$niveaux=$pdo->query("SELECT DISTINCT niveau FROM etudiants ORDER BY niveau")->fetchAll(); $students=[];
if($niveau){$st=$pdo->prepare("SELECT * FROM etudiants WHERE niveau=? ORDER BY nom,prenom");$st->execute([$niveau]);$students=$st->fetchAll();}
include __DIR__ . '/../../includes/header.php'; ?>
<h1 class="page-title mb-3">Saisie des absences</h1><?php if($msg): ?><div class="alert alert-success"><?= e($msg) ?></div><?php endif; ?>
<form method="get" class="card p-3 mb-3"><label class="form-label">Classe / niveau</label><select name="niveau" class="form-select" onchange="this.form.submit()"><option value="">Choisir...</option><?php foreach($niveaux as $n): ?><option <?= $niveau===$n['niveau']?'selected':'' ?>><?= e($n['niveau']) ?></option><?php endforeach; ?></select></form>
<?php if($niveau): ?><form method="post" class="card p-4"><input type="hidden" name="niveau" value="<?= e($niveau) ?>"><div class="row"><div class="col-md-4 mb-3"><label class="form-label">Date</label><input type="date" name="date_absence" class="form-control" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-4 mb-3"><label class="form-label">Heure</label><input type="time" name="heure_absence" class="form-control" value="<?= date('H:i') ?>" required></div><div class="col-md-4 mb-3"><label class="form-label">Type séance</label><select name="type_seance" class="form-select"><option>Cours</option><option>TD</option><option>TP</option><option>Examen</option></select></div></div>
<div class="row"><?php foreach($students as $s): ?><div class="col-md-4"><label class="form-check border rounded p-2 mb-2"><input class="form-check-input ms-0 me-2" type="checkbox" name="etudiants[]" value="<?= $s['id'] ?>"> <?= e($s['nom'].' '.$s['prenom']) ?></label></div><?php endforeach; ?></div><button class="btn btn-primary mt-3">Enregistrer</button></form><?php endif; ?>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
